/* vaccine schedules and information obtained from https://pets.webmd.com/pet-vaccines-schedules-cats-dogs
 * used excel to generate inserts from site table, should in in same directory as destroyCreateDB.sql */

-- dog vaccs
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,1,1,'Rabies 1-year (Adult)', 'Single dose', 'Annual boosters are required.', 'Core dog vaccine. Rabies is 100% fatal to dogs, with no treatment available. Prevention is key.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,1,1,'Rabies 3-year (Adult)', 'Single dose', 'A second vaccination is recommended after 1 year, then boosters every 3 years.', 'Core dog vaccine.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,1,1,'Distemper (Adult)', '2 doses, given 3-4 weeks apart', 'Puppies need a booster 1 year after completing their initial series, then all dogs need a booster every 3 years or more often.', 'Core dog vaccine. Caused by an airborne virus, distemper is a severe disease that, among other problems, may cause permanent brain damage.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,1,1,'Parvovirus (Adult)', '2 doses, 3-4 weeks apart', 'Puppies need a booster 1 year after completing the initial series, then all dogs need a booster every 3 years or more often.', 'Core dog vaccine. Canine "parvo" is contagious, and can cause severe vomiting and bloody diarrhea. Parvo is usually fatal if untreated.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,1,1,'Adenovirus, type 1 (CAV-1, canine hepatitis) (Adult)', 'depends on vaccine', 'Puppies need a booster 1 year after completing the initial series, then all dogs need a booster every 3 years or more often.', 'Core dog vaccine. Spread via infected saliva, urine and feces; canine hepatitis can lead to severe liver damage, and death.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,1,0,'Adenovirus, type 2 (CAV-2, kennel cough) (Adult)', '2 doses, 3-4 weeks apart', 'Puppies need a booster 1 year after completing the initial series, then all dogs need a booster every 3 years or more often.', 'Core dog vaccine. Spread via coughs and sneezes.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,1,0,'Parainfluenza (Adult)', '1 dose', 'A booster may be necessary after 1 year, depending on manufacturer recommendations; revaccination every 3 years is considered protective.', 'Non-core dog vaccine. Parainfluenza infection (not the same as canine influenza) results in cough, fever. It may be associated with Bordetella infection.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,1,0,'Bordetella bronchiseptica (kennel cough) (Adult)', '1 dose of the intranasal or oral product, or 2 doses of the injected product', 'Annual or 6-month boosters may be recommended for dogs in high-risk environments.', 'Non-core dog vaccine. Not usually a serious condition, although it can be dangerous in young puppies. It is usually seen after activities like boarding or showing.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,1,0,'Lyme disease (Adult)', '2 doses, 2-4 weeks apart', 'May be needed annually, prior to the start of tick season', 'Non-core dog vaccine. Generally recommended only for dogs with a high risk for exposure to Lyme disease-carrying ticks.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,1,0,'Leptospirosis (Adult)', '2 doses, 2-4 weeks apart', 'At least once yearly for dogs in high-risk areas', 'Non-core dog vaccine. Vaccination is generally restricted to established risk areas. Exposure to rodents and standing water can lead to a leptospirosis infection.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,1,0,'Canine influenza (Adult)', '2 doses, 2-4 weeks apart', 'Yearly', 'Non-core dog vaccine.Similar to bordetella.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,0,1,'Rabies 1-year (Puppy)', 'Can be administered in one dose, as early as 3 months of age. States regulate the age at which it is first administered.', 'Annual boosters are required.', 'Core dog vaccine. Rabies is 100% fatal to dogs, with no treatment available. Prevention is key.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,0,1,'Rabies 3-year (Puppy)', 'Can be administered as one dose, as early as 3 months of age. States regulate the age at which it is first administered.', 'A second vaccination is recommended after 1 year, then boosters every 3 years.', 'Core dog vaccine.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,0,1,'Distemper (Puppy)', 'At least 3 doses, given between 6 and 16 weeks of age', 'Puppies need a booster 1 year after completing their initial series, then all dogs need a booster every 3 years or more often.', 'Core dog vaccine. Caused by an airborne virus, distemper is a severe disease that, among other problems, may cause permanent brain damage.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,0,1,'Parvovirus (Puppy)', 'At least 3 doses, given between 6 and 16 weeks of age', 'Puppies need a booster 1 year after completing the initial series, then all dogs need a booster every 3 years or more often.', 'Core dog vaccine. Canine "parvo" is contagious, and can cause severe vomiting and bloody diarrhea. Parvo is usually fatal if untreated.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,0,1,'Adenovirus, type 1 (CAV-1, canine hepatitis) (Puppy)', 'Depends on vaccine. For instance, the intranasal one just has to be boostered once a year', 'Puppies need a booster 1 year after completing the initial series, then all dogs need a booster every 3 years or more often.', 'Core dog vaccine. Spread via infected saliva, urine and feces; canine hepatitis can lead to severe liver damage, and death.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,0,0,'Adenovirus, type 2 (CAV-2, kennel cough) (Puppy)', 'At least 3 doses, between 6 and 16 weeks of age', 'Puppies need a booster 1 year after completing the initial series, then all dogs need a booster every 3 years or more often.', 'Core dog vaccine. Spread via coughs and sneezes.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,0,0,'Parainfluenza (Puppy)', 'Administered at 6-8 weeks of age, then every 3-4 weeks until 12-14 weeks old', 'A booster may be necessary after 1 year, depending on manufacturer recommendations; revaccination every 3 years is considered protective.', 'Non-core dog vaccine. Parainfluenza infection (not the same as canine influenza) results in cough, fever. It may be associated with Bordetella infection.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,0,0,'Bordetella bronchiseptica (kennel cough) (Puppy)', 'Depends on the vaccine type; one dose is usually needed for protection', 'Annual or 6-month boosters may be recommended for dogs in high-risk environments.', 'Non-core dog vaccine. Not usually a serious condition, although it can be dangerous in young puppies. It is usually seen after activities like boarding or showing.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,0,0,'Lyme disease (Puppy)', '1 dose, administered as early as 9 weeks, with a second dose 2-4 weeks later', 'May be needed annually, prior to the start of tick season', 'Non-core dog vaccine. Generally recommended only for dogs with a high risk for exposure to Lyme disease-carrying ticks.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,0,0,'Leptospirosis (Puppy)', 'First dose as early as 8 weeks, with a second dose 2-4 weeks later', 'At least once yearly for dogs in high-risk areas', 'Non-core dog vaccine. Vaccination is generally restricted to established risk areas. Exposure to rodents and standing water can lead to a leptospirosis infection.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(1,0,0,'Canine influenza (Puppy)', 'First dose as early as 6-8 weeks; second dose 2-4 weeks later', 'Yearly', 'Non-core dog vaccine.Similar to bordetella.');
-- cat vaccs
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,1,1,'Rabies (Adult)', 'single dose with yearly booster', 'Required annually or every 3 years, depending on vaccine used. State regulations may determine the frequency and type of booster required.', 'Core cat vaccine. Rabies is 100% fatal to cats, with no treatment available. Prevention is key.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,1,1,'Feline Distemper (Panleukopenia) (Adult)', '2 doses, 3-4 weeks apart', '1 dose is given a year after the last dose of the initial series, then every 3 years.', 'Core cat vaccine. Feline distemper is a severe contagious disease that most commonly strikes kittens and can cause death.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,1,1,'Feline Herpesvirus (Adult)', '2 doses, 3-4 weeks apart', '1 dose is given a year after the last dose of the initial series, then every 3 years.', 'Core cat vaccine. Feline herpesvirus causes feline viral rhinotracheitis (FVR), a very contagious upper respiratory condition.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,1,1,'Calicivirus (Adult)', '2 doses, 3-4 weeks apart', '1 dose is given a year after the last dose of the initial series, then every 3 years.', 'Core cat vaccine. A very contagious upper respiratory condition that can cause joint pain, oral ulcerations, fever, and anorexia.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,1,0,'Feline Leukemia Virus (FeLV) (Adult)', '2 doses, 3-4 weeks apart', 'Every kitten should get a booster at one year. If the cat does not go outside, no further vaccination is needed unless they are at higher risk. then annually.', 'Non-core cat vaccine. Should test FeLV negative first. Transmitted via cat-to-cat contact. Can cause cancer, immunosuppressant');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,1,0,'Bordetella (Adult)', '2 doses,1 year apart', 'Annually', 'Non-core cat vaccine. A contagious upper respiratory condition.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,0,1,'Rabies (Kitten)', 'Single dose as early as 8 weeks of age, depending on the product. Revaccinate 1 year later', 'Required annually or every 3 years, depending on vaccine used. State regulations may determine the frequency and type of booster required.', 'Core cat vaccine. Rabies is 100% fatal to cats, with no treatment available. Prevention is key.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,0,1,'Feline Distemper (Panleukopenia) (Kitten)', 'As early as 6 weeks, then every 3-4 weeks until 16 weeks of age', '1 dose is given a year after the last dose of the initial series, then every 3 years.', 'Core cat vaccine. Feline distemper is a severe contagious disease that most commonly strikes kittens and can cause death.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,0,1,'Feline Herpesvirus (Kitten)', 'As early as 6 weeks, then every 3-4 weeks until 16 weeks of age', '1 dose is given a year after the last dose of the initial series, then every 3 years.', 'Core cat vaccine. Feline herpesvirus causes feline viral rhinotracheitis (FVR), a very contagious upper respiratory condition.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,0,1,'Calicivirus (Kitten)', 'As early as 6 weeks, then every 3-4 weeks until 16 weeks of age', '1 dose is given a year after the last dose of the initial series, then every 3 years.', 'Core cat vaccine. A very contagious upper respiratory condition that can cause joint pain, oral ulcerations, fever, and anorexia.');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,0,0,'Feline Leukemia Virus (FeLV) (Kitten)', 'As early as 8 weeks, then 3-4 weeks later', 'Every kitten should get a booster at one year. If the cat does not go outside, no further vaccination is needed unless they are at higher risk. then annually.', 'Non-core cat vaccine. Should test FeLV negative first. Transmitted via cat-to-cat contact. Can cause cancer, immunosuppressant');
INSERT INTO vaccPerSpecies(speciesID, adult, core, vaccName, dosesNote, boosterNote, comment) VALUES(2,0,0,'Bordetella (Kitten)', 'As early as 4 weeks', 'Annually', 'Non-core cat vaccine. A contagious upper respiratory condition.');
-- user can specify details if vaccine not a listed core or non-core vaccine, or not listed at all
INSERT INTO vaccPerSpecies(vaccName) VALUES('Other Vaccine - See additional added notes');
